CREATE SEQUENCE USERS_MASTER_SEQ
INCREMENT BY 50
START WITH 1
MINVALUE 1
MAXVALUE 99999
NOCYCLE
NOCACHE
NOORDER ;

CREATE TABLE USERS_MASTER
(
    ID VARCHAR2(255) NOT NULL PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    CREATE_TIME DATE,
    UPDATE_TIME DATE
);

SELECT * FROM USERS_MASTER;